APPLICATION_NAME = "LIME TBX"
MAIN_QSS_PATH = "assets/style.qss"
QSS_CONSTANTS_PATH = "assets/style_constants.txt"
QSS_DARWIN_CONSTANTS_PATH = "assets/style_constants_darwin.txt"
LOGO_PATH = "assets/lime_logo.png"
ESA_LOGO_PATH = "assets/esa_logo.png"
UVA_LOGO_PATH = "assets/uva_logo.png"
GOA_UVA_LOGO_PATH = "assets/goa_uva_logo.png"
NPL_LOGO_PATH = "assets/npl_logo.png"
VITO_LOGO_PATH = "assets/vito_logo.png"
ESABOLDFONT_PATH = "assets/NotesEsaBol.otf"
ESAFONT_PATH = "assets/NotesEsaReg.otf"
SPINNER_PATH = "assets/spinner.gif"
LIME_SPECTRUM_LIMIT_LABEL = "LIME Spectrum limit"
INTERPOLATED_DATA_LABEL = "Interpolated data points"
ERRORBARS_LABEL = "Errorbars (k=2)"
