interpolation_SRF: Gaussian SRF with 1nm spectral sampling and 3nm resolution
interpolation_spectrum: ASD
interpolation_spectrum_aolp: Linear
interpolation_spectrum_polarisation: Linear
show_cimel_points: true
show_interp_spectrum: false
skip_uncertainties: false
use_wehrli: false
