"""This module contains the values of LIME Toolbox constants."""

MIN_WLEN = 350
MAX_WLEN = 2500
CERTAIN_MIN_WLEN = 350
CERTAIN_MAX_WLEN = 2500
DEFAULT_SRF_NAME = "Default"
EARTH_FRAME = "IAU_EARTH"  # should be "ITRF93"
MOON_FRAME = "IAU_MOON"  # should be "MOON_ME"
VERSION_NAME = "0.1.5"
DEBUG_ENV_NAME = "LIME_DEBUG"
DEV_LOGOUT_ENV_NAME = "LIME_DEVELOPER_LOGGING"
LIME_TBX_DATA_SOURCE = "LIME-TBX"
MAX_LIMIT_REFL_ERR_CORR_ARE_STORED = 25
