#!/usr/bin/env sh
[ -f "/usr/local/bin/lime" ] && rm -f /usr/local/bin/lime
mkdir -p /usr/local/bin
ln -s /Applications/LimeTBX.app/Contents/MacOS/LimeTBX.exe /usr/local/bin/lime
chmod 777 /Applications/LimeTBX.app/Contents/Resources/coeff_data/versions
chmod 777 /Applications/LimeTBX.app/Contents/Resources/coeff_data
chmod 777 /Applications/LimeTBX.app/Contents/Resources/coeff_data/interp_settings.yml
